### ISSUE TITLE
Ubuntu 20.04 for building problems

### ISSUE THREAD

**Issue by Ananhenshuai** [mmtaee/ocserv-users-management#10]
An error is reported after the process is completed，-e Ocserv_Uwsgi Is Not Running.

-e Nginx Is Started.
-e Ocserv Is Started.
-e Ocserv_Uwsgi Is Not Running.

**Comment by zoomd3v** [comment]
i have the same problem

**Comment by rezakeshvari** [comment]
me too have same problem

**Comment by Valdes11** [comment]
mee 2 and no one doesnt like to answer

**Comment by MmdrezaRP** [comment]
I have the same problem Did anybody solve it?

**Comment by 0xb4dc0d3x** [comment]
remove this line
https://github.com/mmtaee/ocserv-users-management/blob/9f3fb8411ff7c93602e971c8304386aebd7afcde/requirements.txt#L3
and add `uwsgi`

like this 
```txt
Django==3.2.14
django-ratelimit==3.0.1
uwsgi
requests
```
