### ISSUE TITLE
ارور گت وی

### ISSUE THREAD

**Issue by DrWampire** [mmtaee/ocserv-users-management#39]
سلام وقت بخیر مهندس جان

دمتون گرم از بابت به وجود آوردن همچین اسکریپتی

من یک مشکلی داشتم همه چیزم کاملا راحت نصب میشه و حتی یک ارور هم توش نیست

ولی موقع اتصال با پوت 20443 تا  Establishing VPN session... آخرین برسی میره

ولی بعد ارور گت وی میده و قطع میکنه اتصالو کل احراز یوزر و همه صحیح میره جلو

توی شل اسکریپت موقع وارد کردن host ip و.. هرجور میزارم چه خالی میزارم چه خودش شناسایی کنه بازم به همین حالت ختم میشه

(((( دیتاسنتر هتزنر هستش روی ابنتو 20.04 چه با تونل چه بدون تونل به همین شکله کلا

ممنون میشم محبت کنی راهنمایی کنی ، دلم نمیاد پنل با این جزئیاتی رو ولکنم 👍💕

**Comment by mmtaee** [comment]
سلام . 
امکانش هست لاگ سمت سرور و کلاینت رو ارسال کنید تا بتونم کمکتون کنم

**Comment by DrWampire** [comment]
سلام وقت بخیر

من بعد چند وقت از یک دیتاسنتر دیگه هم تست گرفتم نتیجه شد بازم مثل قبلی

عکس هارو هم خدمتتون پیوست زدم ، فقط از اونجایی که استفاده بروی مودم ADSL انجام شده احتمال داره تو جزئیات متوجه سرور ایرانی که فوروارد شده بهش بشین که خواستم از این مورد اگه چیز خاصی مشاهده کردین برای این موضوع بوده...

سپاس.
![pic1](https://github.com/mmtaee/ocserv-users-management/assets/96009307/16ba83e2-5ec0-4416-a0f2-36f36347e876)
![pic2](https://github.com/mmtaee/ocserv-users-management/assets/96009307/32a22e5e-28db-4b6a-a8fb-5b0a027fee8b)
![Screenshot 2024-02-02 014546](https://github.com/mmtaee/ocserv-users-management/assets/96009307/6d6ac079-1539-4a7c-bab0-35a09eddddac)

**Comment by mmtaee** [comment]
احتمالا مشکل tls دارید. خط کانفیگ tls رو با خط کامنت شده جابجا کنید و کانتینر رو ری استارت . احتمالا مشکل رفع می شود
