### ISSUE TITLE
we need this script on centos7

### ISSUE THREAD

**Issue by nginxweb** [mmtaee/ocserv-users-management#4]
hi
Please make this code compatible with centos7 as we use centos7 and desperately need this script

**Comment by nginxweb** [comment]
Can you publish only panel installation tutorial?

**Comment by mmtaee** [comment]
Django app database is SQLite3 and SQLite is not compatible with Centos 7.

**Comment by mmtaee** [comment]
> hi
> Please make this code compatible with centos7 as we use centos7 and desperately need this script

Django app database is SQLite3 and SQLite is not compatible with Centos 7.
