### ISSUE TITLE
The VPN configuration received from the secure gateway is invalid.

### ISSUE THREAD

**Issue by mehdiala** [mmtaee/ocserv-users-management#40]
با احترام
در ابتدا تشکر میکنم بابت این انتشار 
بعد از نصب کامل برنامه و ساخت یوزر تست،بعد از اتصال به سرور از طریق کلاینت anyconnect و انجام احراز هویت با این خطا که در عنوان مطرح شده مواجه میشم.روی بیش از 4 سرور مختلف هم تست کردم.ولی نسخه قدیمی تر همین برنامه شما (حدودا 6 ماه پیش) همچین مشکلی رو نداشت.
نحوه نصب من بدین صورت بود 
git clone https://github.com/mmtaee/ocserv-users-management.git
cd /root/ocserv-users-management/
chmod +x install.sh && ./install.sh
و انتخاب گزینه دوم که ocserv+panel هست.
ممنون میشم راهنمایی کنید مشکل از کجا میتونه باشه.

**Comment by mmtaee** [comment]
سلام . 
احتمال زیاد مشکل شما برای TLS هست این دو خط رو در کانیگ ها پیدا کنید . خط دوم که کامنت هست رو از حالت کامنت خارج کنید . خط اولی رو کامنت کنید. سرویس رو ری استارت کنید احتمالا مشکل برطرف میشه 
```
# /etc/ocser/ocserv.conf

tls-priorities="NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0"
#tls-priorities="NORMAL:%SERVER_PRECEDENCE:%COMPAT:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1"
```
