### ISSUE TITLE
System Logs & Services

### ISSUE THREAD

**Issue by ohum123** [mmtaee/ocserv-users-management#43]
اول مرسی بابت کامیت قبلی
وقتی توی پنل روی ocserv systemd کلیک میشه:
سرویس backend:
Feb 02 22:27:03 PS1705774090 uwsgi[28184]: sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
Feb 02 22:27:03 PS1705774090 sudo[28184]: pam_unix(sudo:auth): conversation failed
Feb 02 22:27:03 PS1705774090 sudo[28184]: pam_unix(sudo:auth): auth could not identify password for [www-data]
Feb 02 22:27:03 PS1705774090 sudo[28184]: www-data : command not allowed ; TTY=unknown ; PWD=/var/www/site/back-end ; USER=root ; COMMAND=/usr/bin/systemctl status ocserv.service --output=json-pretty
همچنین توی دشبورد نه Online users نه show status چیزی نشون داده نمیشه

**Comment by ohum123** [comment]
یه نکته هم بگم که من از قبل یوزر داشتم و توی ocpasswd هستن یوزرا ، اگه امکانش بود که یوزرای توی db و ocpasswd با هم سینک میشدن فک میکنم مشکل حل میشد.

**Comment by mmtaee** [comment]
> یه نکته هم بگم که من از قبل یوزر داشتم و توی ocpasswd هستن یوزرا ، اگه امکانش بود که یوزرای توی db و ocpasswd با هم سینک میشدن فک میکنم مشکل حل میشد.

check this commit [f147d404]
