### ISSUE TITLE
search_strings

### ISSUE THREAD

**Issue by ohum123** [mmtaee/ocserv-users-management#44]
توی user state
خط search_strings = ["reason: user disconnected", "rx", "tx"]
با search_strings = ["reason: ", "rx", "tx"] جایگزین بشه
چون ممکنه یوزر خودش قطع نکنه کانکشن رو اونوقت توی کانتر نمیافته

**Comment by mmtaee** [comment]
مقادیر rx و tx  در هر خط لاگ در حال افزایش هستند و این مقادیر مصرف تا اون لحظه هست . اگر این خط حذف شود . مقادیر مصرفی کاربر عدد حقیقی مصرف نمی شود. به هر دلیلی اتصال کاربر قطع شود لاگ  reason: user disconnected به سرویس ارسال می شود . پس مشکلی بوجود نمی آورد. اگر نکته دیگه یا موردی خلاف این رو مشاهده کردید لطفا لاگ بفرستید تا بررسی کنیم .
