### ISSUE TITLE
code bug  

### ISSUE THREAD

**Issue by microbull** [mmtaee/ocserv-users-management#47]
BUG 
WEB  'Create Ocserv Group' AND  'Configuration'      page     All of the   'routes'    write to config file is 
routes=192.168.0.0/24  is  incorrect,
route =192.168.0.0/24  is correct.need fix.

Question
if i want reinstall ocserv how can i backup all data include WEB and ocserv ?

how can i restore admin password.
How do I add more administrators?

**Comment by mmtaee** [comment]
```Question
if i want reinstall ocserv how can i backup all data include WEB and ocserv ?
```
-- in docker mode you need copy volume directory. 
after paste directory restart docker compose 

-- in systemd mode: 
copy database in dir : /var/www/site/back-end/db/*
copy /etc/ocserv/* 

after reinstall 
paste files and dirs then restart services:
1. ocserv.service                               `# for changes in /etc/ocserv/* `
2. backend.service                            `# for changes in /var/www/site/back-end/db/*`
3. user_stats.service                         `# for changes in /var/www/site/back-end/db/*`
