### ISSUE TITLE
Can you go back to the previous version

### ISSUE THREAD

**Issue by microbull** [mmtaee/ocserv-users-management#52]
lastest version   stop at login page   the previous version only a little text error
![image](https://github.com/mmtaee/ocserv-users-management/assets/162737500/318ab792-13fe-4b22-ac3c-0466fca45ab7)

**Comment by mmtaee** [comment]
can you send me a pic from your browser console and network ?

**Comment by microbull** [comment]
if i use yesterday version it shoud be stop at seeting admin page.this is the pic after fresh install .i hope it will be help you to fix it.
 



| |
刘权
|
|
***@***.***
|
---- Replied Message ----
| From | Masoud ***@***.***> |
| Date | 3/16/2024 18:24 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [mmtaee/ocserv-users-management] Can you go back to the previous version (Issue #52) |

can you send me a pic from your browser console and network ?

**Comment by microbull** [comment]
| |
刘权
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/16/2024 21:09 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [mmtaee/ocserv-users-management] Can you go back to the previous version (Issue #52) |


if i use yesterday version it shoud be stop at seeting admin page.this is the pic after fresh install .i hope it will be help you to fix it.
 



| |
刘权
|
|
***@***.***
|
---- Replied Message ----
| From | Masoud ***@***.***> |
| Date | 3/16/2024 18:24 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [mmtaee/ocserv-users-management] Can you go back to the previous version (Issue #52) |

can you send me a pic from your browser console and network ?
